site_name: raSCSI VPN Network Attached Storage
site_url: https://example.com/
theme:
    name: readthedocs
nav:
    - Home: index.md
    - Rascsi: rascsi.md
    - Netatalk: netatalk.md
    - Tailscale: tailscale.md
    - Samba: samba.md
    - Mac Software: macsw.md
    - References: references.md
    
markdown_extensions:
  - attr_list